package com.monkey.finder.find.dao;

import com.monkey.finder.find.entity.Items;

public interface ItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_items
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_items
     *
     * @mbggenerated
     */
    int insert(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_items
     *
     * @mbggenerated
     */
    int insertSelective(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_items
     *
     * @mbggenerated
     */
    Items selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_items
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Items record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_items
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Items record);

    Items selectById(Long itemId);

    void offbaseDecr(Long itemId);
}