package com.monkey.finder.find.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

@ApiModel(value="com.monkey.finder.find.entity.Account")
public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_account.user_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="userId用户id")
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_account.user_email
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="userEmail用户注册用邮箱不可以为空")
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_account.salt
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="saltyan")
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_account.state
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="state0 未验证 1 已验证")
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_account.user_password
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="userPassword用户密码 yan + 密码")
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_account.regis_date
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="regisDate注册时间")
    private Date regisDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_account.user_id
     *
     * @return the value of find_account.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_account.user_id
     *
     * @param userId the value for find_account.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_account.user_email
     *
     * @return the value of find_account.user_email
     *
     * @mbggenerated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_account.user_email
     *
     * @param userEmail the value for find_account.user_email
     *
     * @mbggenerated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_account.salt
     *
     * @return the value of find_account.salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_account.salt
     *
     * @param salt the value for find_account.salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_account.state
     *
     * @return the value of find_account.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_account.state
     *
     * @param state the value for find_account.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_account.user_password
     *
     * @return the value of find_account.user_password
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_account.user_password
     *
     * @param userPassword the value for find_account.user_password
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_account.regis_date
     *
     * @return the value of find_account.regis_date
     *
     * @mbggenerated
     */
    public Date getRegisDate() {
        return regisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_account.regis_date
     *
     * @param regisDate the value for find_account.regis_date
     *
     * @mbggenerated
     */
    public void setRegisDate(Date regisDate) {
        this.regisDate = regisDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_account
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userEmail=").append(userEmail);
        sb.append(", salt=").append(salt);
        sb.append(", state=").append(state);
        sb.append(", userPassword=").append(userPassword);
        sb.append(", regisDate=").append(regisDate);
        sb.append("]");
        return sb.toString();
    }
}