package com.monkey.finder.find.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

@ApiModel(value="Items")
public class Items {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_items.item_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="itemId物品id")
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_items.user_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="userId拾取者id")
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_items.item_info
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="itemInfo物品描述")
    private String itemInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_items.lost_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="lostTime丢失时间")
    private Date lostTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_items.wchat
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="wchat联系微信")
    private String wchat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_items.phone
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="phone联系电话")
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_items.off_base
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="offBase下线基数 ")
    private Integer offBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_items.record_state
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="recordState0 无效 1 有效")
    private Integer recordState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_items.lon
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="lon经度")
    private String lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_items.lat
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="lat纬度")
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column find_items.item_img
     *
     * @mbggenerated
     */
    @ApiModelProperty(value="itemImg物品图片")
    private String itemImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_items.item_id
     *
     * @return the value of find_items.item_id
     *
     * @mbggenerated
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_items.item_id
     *
     * @param itemId the value for find_items.item_id
     *
     * @mbggenerated
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_items.user_id
     *
     * @return the value of find_items.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_items.user_id
     *
     * @param userId the value for find_items.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_items.item_info
     *
     * @return the value of find_items.item_info
     *
     * @mbggenerated
     */
    public String getItemInfo() {
        return itemInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_items.item_info
     *
     * @param itemInfo the value for find_items.item_info
     *
     * @mbggenerated
     */
    public void setItemInfo(String itemInfo) {
        this.itemInfo = itemInfo == null ? null : itemInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_items.lost_time
     *
     * @return the value of find_items.lost_time
     *
     * @mbggenerated
     */
    public Date getLostTime() {
        return lostTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_items.lost_time
     *
     * @param lostTime the value for find_items.lost_time
     *
     * @mbggenerated
     */
    public void setLostTime(Date lostTime) {
        this.lostTime = lostTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_items.wchat
     *
     * @return the value of find_items.wchat
     *
     * @mbggenerated
     */
    public String getWchat() {
        return wchat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_items.wchat
     *
     * @param wchat the value for find_items.wchat
     *
     * @mbggenerated
     */
    public void setWchat(String wchat) {
        this.wchat = wchat == null ? null : wchat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_items.phone
     *
     * @return the value of find_items.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_items.phone
     *
     * @param phone the value for find_items.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_items.off_base
     *
     * @return the value of find_items.off_base
     *
     * @mbggenerated
     */
    public Integer getOffBase() {
        return offBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_items.off_base
     *
     * @param offBase the value for find_items.off_base
     *
     * @mbggenerated
     */
    public void setOffBase(Integer offBase) {
        this.offBase = offBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_items.record_state
     *
     * @return the value of find_items.record_state
     *
     * @mbggenerated
     */
    public Integer getRecordState() {
        return recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_items.record_state
     *
     * @param recordState the value for find_items.record_state
     *
     * @mbggenerated
     */
    public void setRecordState(Integer recordState) {
        this.recordState = recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_items.lon
     *
     * @return the value of find_items.lon
     *
     * @mbggenerated
     */
    public String getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_items.lon
     *
     * @param lon the value for find_items.lon
     *
     * @mbggenerated
     */
    public void setLon(String lon) {
        this.lon = lon == null ? null : lon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_items.lat
     *
     * @return the value of find_items.lat
     *
     * @mbggenerated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_items.lat
     *
     * @param lat the value for find_items.lat
     *
     * @mbggenerated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column find_items.item_img
     *
     * @return the value of find_items.item_img
     *
     * @mbggenerated
     */
    public String getItemImg() {
        return itemImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column find_items.item_img
     *
     * @param itemImg the value for find_items.item_img
     *
     * @mbggenerated
     */
    public void setItemImg(String itemImg) {
        this.itemImg = itemImg == null ? null : itemImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table find_items
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", itemId=").append(itemId);
        sb.append(", userId=").append(userId);
        sb.append(", itemInfo=").append(itemInfo);
        sb.append(", lostTime=").append(lostTime);
        sb.append(", wchat=").append(wchat);
        sb.append(", phone=").append(phone);
        sb.append(", offBase=").append(offBase);
        sb.append(", recordState=").append(recordState);
        sb.append(", lon=").append(lon);
        sb.append(", lat=").append(lat);
        sb.append(", itemImg=").append(itemImg);
        sb.append("]");
        return sb.toString();
    }
}